version: '3.8'

services:
    alpine:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony_docker
        restart: on-failure
        ports:
            - "1234:80"
        volumes:
            - ./conf/site.conf:/etc/nginx/http.d/default.conf
            - ./src:/var/www/html
        networks:
            - acpSymfony

    db:
        image: mariadb:10.8.2
        container_name: mariadb_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: 'ChangeMeLater'
        networks:
            - acpSymfony

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1

volumes:
    db-data:

networks:
    acpSymfony:
