<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVyCfAl9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVyCfAl9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVyCfAl9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVyCfAl9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVyCfAl9\App_KernelDevDebugContainer([
    'container.build_hash' => 'VyCfAl9',
    'container.build_id' => '008ddcab',
    'container.build_time' => 1666904910,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVyCfAl9');
