<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLZPxuP3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLZPxuP3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLZPxuP3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLZPxuP3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLZPxuP3\App_KernelDevDebugContainer([
    'container.build_hash' => 'LZPxuP3',
    'container.build_id' => '152c1e58',
    'container.build_time' => 1666772044,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLZPxuP3');
